site_name: Jogos Avançados
site_url: https://lpsoares.github.io/JogosAvancados
theme:
  name: material

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - callouts


nav:
    - Home: index.md

    - Aulas:
        - "01 - Introdução": aulas/01-introducao/index.md
        - "02 - Blockmesh":
            - "Aula": aulas/02-blockmesh/index.md
            - "Atividade Blockmesh": aulas/02-blockmesh/blockmesh.md
        - "03 - Terrenos": aulas/03-terrenos/index.md
        - "04 - Iluminação": aulas/04-iluminacao/index.md
        - "05 - Blueprints":
          - "Aula": aulas/05-blueprints/index.md
          - "Atividade Blueprints": aulas/05-blueprints/blueprints.md
        - "06 - Inteligência Artificial":
          - "Aula": aulas/06-ia/index.md

